## <center>Знаходження власних чисел та власних векторів матриць</center>

### 1. Метод обертань Якобі для симетричних матриць

<img src="jacobi.png"  align="left"/>, 

де **T** - матриця обертання Гівенса, яка занулює елемент максимальний за модулем елемент матриці **B**

In [172]:
import numpy as np
from scipy import linalg
np.set_printoptions(precision=4, suppress=True)

In [173]:
A = np.array([\
              [1.4,   1, 1.2],\
              [1,   2.1,   2],\
              [1.2,   2, 2.5],\
             ])

In [2]:
def jacobi_rotation(A, j, k, J):
    r = (A[j, j] - A[k,k])/(2*A[j,k])
    t = np.sign(r)/(np.abs(r) + (1+r**2)**0.5)
    c = 1/((1+t**2)**0.5)
    s = c*t
    R = np.identity(len(A))
    R[j,j] = c 
    R[j,k] = -s
    R[k,j] = s
    R[k,k] = c
    A = np.matmul(np.matmul(R.T, A), R)
    J = np.matmul(J, R)
    return A, J

In [239]:
def jacobi_eigen(A, eps = 0.0001):
    V = A.copy()
    np.fill_diagonal(V,0)
    J = np.identity(len(A))
    
    while np.linalg.norm(V, 'fro') > eps:
        j,k = np.unravel_index(np.argmax(np.abs(V)),A.shape)
        
        print("Опорный элекмент: ", A[j,k])
        print("След: ", np.trace(A))
        print("Евклидова норма: ", np.linalg.norm(A,'fro'))
        
        if (np.abs(A[j,k])<eps):
            break
        A, J = jacobi_rotation(A,j,k,J)

        print("\n")
        V = A.copy()
        np.fill_diagonal(V,0)
        
    j,k = np.unravel_index(np.argmax(np.abs(V)),A.shape)
    print("Опорный элекмент: ", A[j,k])
    print("След: ", np.trace(A))
    print("Евклидова норма: ", np.linalg.norm(A,'fro'))
    print("\n")
    return A, J
        

In [240]:
D, Q = jacobi_eigen(A.copy(),0.0001)

Опорный элекмент:  2.0
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  1.56074836102
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  -0.058464221439
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  -0.0252036052054
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  0.00335653638705
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  1.79739164645e-05
След:  6.0
Евклидова норма:  5.04975246918




Матриця власних чисел:

In [188]:
print(D)

[[ 0.729   0.     -0.    ]
 [ 0.      0.2821  0.    ]
 [ 0.      0.      4.9889]]


Ортогональна матриця власних векторів:

In [189]:
Q

array([[ 0.9087,  0.1232,  0.3989],
       [-0.3636,  0.7029,  0.6113],
       [-0.2051, -0.7005,  0.6835]])

Перевіримо співвідношення ***QtQ=E*** та ***QDQt = A*** 

In [192]:
Q.T.dot(Q)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [193]:
Q.dot(D).dot(Q.T)

array([[ 1.4,  1. ,  1.2],
       [ 1. ,  2.1,  2. ],
       [ 1.2,  2. ,  2.5]])

#### Порядок збіжності:

In [242]:
D, Q = jacobi_eigen(A.copy(),10**(-15))

Опорный элекмент:  2.0
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  1.56074836102
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  -0.058464221439
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  -0.0252036052054
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  0.00335653638705
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  1.79739164645e-05
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  1.41624359591e-08
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  5.69588779613e-13
След:  6.0
Евклидова норма:  5.04975246918


Опорный элекмент:  -4.36140778404e-16
След:  6.0
Евклидова норма:  5.04975246918




Очевидно, що порядок збіжності швидше лінійного

### QR-алгоритм знаходження власних значень несиметричиних матриць

<img src="qr1.png"  align="left"/>

<img src="qr2.png"  align="left"/> 

In [247]:
A = np.array([\
              [1, 0, 0, 0],\
              [0, 2, 0, 0],\
              [0, 0, 3, 0],\
              [0, 0, 0, 4]\
             ])

In [248]:
S = np.array([[-5,4,1,0],[2,3,-2,1],[0,7,-4,-3],[1,4,0,6]])

In [249]:
S_inv = np.linalg.inv(S)

In [250]:
A = S.dot(A).dot(S_inv)

**Исходная матрица**

In [251]:
A

array([[-20.   , -64.5  ,  26.5  ,  24.   ],
       [ 22.25 ,  68.875, -27.375, -24.5  ],
       [ 10.25 ,  31.875, -10.375, -12.5  ],
       [ 28.75 ,  86.625, -36.125, -28.5  ]])

Для зменшення кількості арифметичних операцій матрицю попередньо зводять до форми Хесенберга за допомогою перетворень Хаусхолдера

In [145]:
def house(A, i): #матрица Хаусхолдера для обнуление элементов под второй диагональю матрицы
    b = np.sign(-A[i+1, i])*np.linalg.norm(A[i+1:,i])
    mu = 1/( (2*b**2-2*A[i+1,i]*b)**0.5 )
    w = np.array(A[:,i])
    w[i+1] = A[i+1,i] - b
    w[:(i+1)] = 0
    w = mu*w
    w = np.expand_dims(w,axis=1)
    H = np.identity(len(A)) - 2*w.dot(w.T)
    return H

In [252]:
def hessenberg(A): #приведение матрицы к форме Хессенберга
    result = A.copy()
    for i in range(len(A)-2):
        H = house(result,i)
        result = H.dot(result).dot(H.T)
    return result

In [244]:
def givens_rotation(H, i): #обнуление элемента второй диагонали матрицы Хессенберга
    eps = 10**(-4)
    T = np.identity(len(H))
    if abs(H[i,i])<eps:
        s = 0
        c = 1
    else:
        t = H[i+1,i]/H[i,i]
        c = 1/(1+t**2)**0.5
        s = t/(1+t**2)**0.5
    T[i,i]   =   c
    T[i,i+1] =   s
    T[i+1,i] =  -s
    T[i+1,i+1] = c
    return (T, T.dot(H))

In [245]:
def QR_eigen(A):
    eps = 10**(-4)
    H = hessenberg(A)
    print("Матриця Хесенберга: ")
    print(H)
    while (abs(max(np.diag(H, -1)))>eps):
        Q = np.identity(len(A))
        for i in range(len(H)-1):
            Qi,H = givens_rotation(H,i)
            Q = Qi.dot(Q)
        Q = Q.T #A = QH
        H = H.dot(Q)
    return np.diag(H)
    

In [253]:
QR_eigen(A)

Матриця Хесенберга: 
[[ -20.       12.5359   31.7709   65.3603]
 [ -37.7715   25.1548   55.2124  115.3172]
 [   0.       -0.6298    3.5061    0.1788]
 [   0.       -0.       -0.8471    1.3391]]


array([ 4.,  3.,  2.,  1.])

**Висновки:** для пошуку спектру симетричних матриць використовується метод обертань Якобі. Для несиметричних - QR-алгоритм. Для прискорення обчислень за QR-алгоритмом матриця попередньо приводиться до форми Хессенберга