In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=5)

In [3]:
def lin_svd(A, b):
    U, S, V = np.linalg.svd(A)
    print("U\n",U)
    print("S\n", S)
    print("V\n", V)
    singular_values = S[abs(S)>10**(-4)]
    print("singular_values: ", singular_values)
    S[abs(S)<10**(-4)] = 0
    rg = np.count_nonzero(S)
    print('Ранг: ', rg)
    cond = max(singular_values)/min(singular_values)
    print('Число обусловленности: ',cond)
    z = U.T@b
    z[abs(z)<10**(-4)] = 0
    print('z = ', z)
    if rg == len(A):
        print("Ранг системы равен размерности матрицы, поэтому системы совместны и имеют единственное решение: ")
        y = z/S
        x = V.T@y
        print('Решение системы: ', x)
        return x
    z[abs(z)<10**(-4)] = 0
    if (np.count_nonzero(z)==rg):
        print("Система имеет бесконечное число решений")
        y = np.zeros(len(z))
        y1 = z[z!=0]/singular_values
        y[:len(y1)] = y1
        x = V.T@y
        print('Частичное решение: x = ', x)
        print('Общее решение: x+C1*{1}+C2*{2}'.format(x, V[2], V[3]))
        return x
    if (np.count_nonzero(z)>rg):
        print("Система несовместна, ищем псевдорешение: ")
        y = np.zeros(len(z))
        y1 = z[:len(singular_values)]/singular_values
        y[:len(y1)] = y1
        x = V.T@y
        print('Псевдорешение: x= ', x)
        print('Невязка: ', A@x-b)

In [4]:
A = np.array([[2,7,3,1],\
              [1,3,5, -2],\
              [1, 5, -9, 8],\
              [5, 18, 4, 5]])
b = np.array([5, 3, 1, 12])

In [5]:
lin_svd(A,b)

U
 [[-0.34131 -0.18492  0.92157 -0.00557]
 [-0.13562 -0.4164  -0.13915 -0.88818]
 [-0.27576  0.87936  0.07202 -0.38144]
 [-0.8883  -0.13836 -0.3552   0.25615]]
S
 [2.21372e+01 1.31509e+01 1.46656e-15 3.51364e-16]
V
 [[-0.25005 -0.91087 -0.12528 -0.30346]
 [-0.04552 -0.04847 -0.84439  0.53159]
 [-0.84396  0.04446  0.3149   0.43197]
 [ 0.47237 -0.40741  0.41492  0.66237]]
singular_values:  [22.13715 13.15091]
Ранг:  2
Число обусловленности:  1.6833175857827956
z =  [-13.04872  -2.95479   0.        0.     ]
Система имеет бесконечное число решений
Частичное решение: x =  [0.15762 0.5478  0.26357 0.05943]
Общее решение: x+C1*[-0.84396  0.04446  0.3149   0.43197]+C2*[ 0.47237 -0.40741  0.41492  0.66237]


array([0.15762, 0.5478 , 0.26357, 0.05943])

In [6]:
A = np.array([[4, -3, 2, -1],\
              [3, -2, 1, -3],\
              [2, -1, 0, -5],\
              [5, -3, 1, -8]])
b = np.array([8,7,6,1])

In [7]:
lin_svd(A,b)

U
 [[-0.33163  0.84472 -0.37091 -0.19722]
 [-0.36721  0.20402  0.88924 -0.18107]
 [-0.4028  -0.43668 -0.2235  -0.77273]
 [-0.77002 -0.23266 -0.14741  0.57551]]
S
 [1.28630e+01 4.06718e+00 3.66503e-16 1.43612e-16]
V
 [[-0.55071  0.34534 -0.13997  0.7469 ]
 [ 0.4805  -0.44442  0.40834  0.6363 ]
 [ 0.62203  0.77673 -0.03224  0.09347]
 [-0.28092  0.28271  0.90146 -0.16891]]
singular_values:  [12.86305  4.06718]
Ранг:  2
Число обусловленности:  3.16264525915081
z =  [-8.41035  5.33315  1.76897 -6.9061 ]
Система несовместна, ищем псевдорешение: 
Псевдорешение: x=  [ 0.99014 -0.80855  0.62696  0.346  ]
Невязка:  [-0.70588 -2.82353 -4.94118  4.23529]


**Выводы:** SVD - разложение может использоваться для решение систем СЛАУ, особенно в случае, когда система недоопределена или переопределена. В первом случае, система может иметь бесконечное множество решений, и SVD позволяет выписать решение в общем виде. Во втором случае, с помощью SVD можно найти нормальное псевдорешение, как минимум нормы невязки.